	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Overlight</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- ESTILOS DE MENU DE NAVEGACIÓN -->
	<link rel="stylesheet" href="../../css/cssmenunav/bootstrappanelMOSTRAR.css">
    <link rel="stylesheet" href="../../css/cssmenunav/bootstrap-theme.css" media="screen" >
    <link rel="stylesheet" type="text/css"  href="../../css/cssmenunav/style.css">
	<!-- ESTILOS DE FONDO-IMAGEN-->
	<link rel="stylesheet" href="../../css/cssfondo/responsive-full-background-image.css">
	<!-- JavaScript DE MENU DE NAVEGACIÓN-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="../../js/jsmununav/bootstrap.js"></script>
	<script type="text/javascript" src="../../js/jsadmin/tab.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="../../js/jsmenunav/bootstrapmenunav.js"></script>
	<script src="../../js/jsadmin/jquery-1.11.3.min.js"></script>
	<script src="../../js/jsadmin/bootstrap.min.js"></script>
	
	
	<script type="text/javascript" src="../../js/jsregistro/validarregistro.js"></script>
    <script type="text/javascript" src="../../js/jsadmin/valletras.js"></script>
    <script type="text/javascript" src="../../js/jsadmin/valnum.js"></script>
    <script type="text/javascript" src="../../js/jsadmin/bloqueoespecial.js"></script>